### ISSUE TITLE
Duplicate appearance of the plugin in the menue

### ISSUE THREAD

**Issue by Stvad** [dayjaby/AnkiHub#1]
![screenshot_20160910_203454](https://cloud.githubusercontent.com/assets/81347/18412759/46305e52-7797-11e6-8423-011319c6a723.png)
Version was the latest available on AnkiWeb (and it updated itself to v2.0 on first launch).

**Comment by dayjaby** [comment]
You have an ___ankihub.py (the newer version) and ankihub.py (older version) in your addons directory. I renamed it so that AnkiHub gets started before other plugins, in the hope that it updates the other plugins before they get started, removing the necessity of restarting Anki after updating.

**Comment by Stvad** [comment]
You should update version on AnkiWeb, so users won't get 2 of them :).
I see, it is still not guaranteed, though ;) And I'm not sure it's the best way to do it anyway, as I mentioned here: https://www.reddit.com/r/Anki/comments/51xljb/ankihub_automatic_plugin_updater_based_on_github/d7h0jbv

**Comment by dayjaby** [comment]
Eh, fixed! Thanks for testing that.
